services:
  postgres:
    image: postgres:16
    container_name: ordersphere-postgres
    environment:
      POSTGRES_USER: ordersphere
      POSTGRES_PASSWORD: ordersphere
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres-init:/docker-entrypoint-initdb.d

  service-registry:
    build:
      context: .
      dockerfile: services/service-registry/Dockerfile
    container_name: ordersphere-service-registry
    ports:
      - "8761:8761"

  ordersphere-gateway:
    build:
      context: .
      dockerfile: services/ordersphere-gateway/Dockerfile
    container_name: ordersphere-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
    depends_on:
      - service-registry

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    container_name: ordersphere-auth-service
    ports:
      - "8081:8081"
    environment:
      DB_HOST: postgres
      DB_NAME: auth_db
      DB_USERNAME: ordersphere
      DB_PASSWORD: ordersphere
      JWT_SECRET: ${JWT_SECRET:-dev-only-secret-key-change-me-before-any-real-deployment}
      EUREKA_URI: http://service-registry:8761/eureka
    depends_on:
      - postgres
      - service-registry

  inventory-service:
    build:
      context: .
      dockerfile: services/inventory-service/Dockerfile
    container_name: ordersphere-inventory-service
    ports:
      - "8083:8083"
    environment:
      DB_HOST: postgres
      DB_NAME: inventory_db
      DB_USERNAME: ordersphere
      DB_PASSWORD: ordersphere
      JWT_SECRET: ${JWT_SECRET:-dev-only-secret-key-change-me-before-any-real-deployment}
      EUREKA_URI: http://service-registry:8761/eureka
    depends_on:
      - postgres
      - service-registry

volumes:
  postgres-data:
