apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ordersphere
type: Opaque
stringData:
  POSTGRES_DB: ordersphere_auth
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

