package com.ordersphere.notification.domain;

public enum TemplateKey {
  ORDER_CONFIRMED,
  ORDER_CANCELLED,
  PAYMENT_COMPLETED,
  PAYMENT_FAILED,
  SHIPMENT_CREATED,
  SHIPMENT_PICKED,
  SHIPMENT_IN_TRANSIT,
  DELIVERY_CONFIRMED,
  STOCK_LOW
}
