apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-registry.yaml
  - ordersphere-gateway.yaml
  - auth-service.yaml
  - inventory-service.yaml
  - ordersphere-orders.yaml
  - payment-service.yaml
  - shipping-service.yaml
  - notification-service.yaml
  - dummy-payment-gateway.yaml
