apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordersphere-auth
  namespace: ordersphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordersphere-auth
  template:
    metadata:
      labels:
        app: ordersphere-auth
    spec:
      containers:
        - name: ordersphere-auth
          image: ordersphere-auth:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/ordersphere_auth
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres



